<a href="https://colab.research.google.com/github/kmrzakir/car_price_predector/blob/main/car_price_predector.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('/content/quikr_car.csv')

df.shape

(892, 6)

In [ ]:
df_copy = df.copy()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 892 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        892 non-null    object
 1   company     892 non-null    object
 2   year        892 non-null    object
 3   Price       892 non-null    object
 4   kms_driven  840 non-null    object
 5   fuel_type   837 non-null    object
dtypes: object(6)
memory usage: 41.9+ KB

In [ ]:
df_copy = df.copy()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 892 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        892 non-null    object
 1   company     892 non-null    object
 2   year        892 non-null    object
 3   Price       892 non-null    object
 4   kms_driven  840 non-null    object
 5   fuel_type   837 non-null    object
dtypes: object(6)
memory usage: 41.9+ KB

In [ ]:
print(df['kms_driven'].isnull().sum())

52

# **Data Cleaning**


1.   From name column get only first three words of name
2.   From years column remove all string value
3.   From Price column replace , with '' and alo remove string values and alo convert it into numeric form
4. From kms_driven remove kms string and alo , and convert into numeric
5. From fuel_type colun remove null

In [ ]:
df['name'] = df['name'].str.split(' ').str.slice(0,3).str.join(' ')

In [ ]:
df = df[df['year'].str.isnumeric()]
df['year'] = pd.to_numeric(df['year'])

In [ ]:
df = df[df['Price'] != 'Ask For Price']
df['Price'] = df['Price'].str.replace(',','')
df['Price'] = pd.to_numeric(df['Price'])

In [ ]:
df['kms_driven']=df['kms_driven'].str.split(' ').str[0]
df['kms_driven'] = df['kms_driven'].str.replace(',','')
df = df[df['kms_driven'] != 'Petrol']
df['kms_driven'] = pd.to_numeric(df['kms_driven'])

In [ ]:
df.dropna(subset=['kms_driven'], inplace=True)

In [ ]:
df = df[df['fuel_type'].notnull()]

In [ ]:
df = df.reset_index(drop=True)

In [ ]:
df.to_csv('clean_data.csv', index=False)

In [ ]:
df.sample(10)

                         name     company  year   Price  kms_driven fuel_type
762            Tata Indica V2        Tata  2005   60000       80000    Diesel
702       Hyundai Santro Xing     Hyundai  2007  135000       47000    Petrol
403        Mahindra TUV300 T4    Mahindra  2017  610000       68000    Diesel
812            Tata Indica V2        Tata  2009  110000       30000    Diesel
215           Volkswagen Polo  Volkswagen  2015  330000       38000    Diesel
174       Maruti Suzuki Wagon      Maruti  2012  199999       44000    Petrol
114       Maruti Suzuki Dzire      Maruti  2009  220000       46000    Petrol
345        Hyundai i10 Sportz     Hyundai  2012  230000       34000    Petrol
64   Volkswagen Polo Highline  Volkswagen  2014  315000       60000    Petrol
265       Maruti Suzuki Dzire      Maruti  2013  380000       30000    Petrol

In [ ]:
df["year"].unique()

array([2007, 2006, 2014, 2012, 2013, 2016, 2015, 2010, 2017, 2008, 2018,
       2011, 2019, 2009, 2005, 2000, 2003, 2004, 1995, 2002, 2001])

In [ ]:
df["year"].unique()

array([2007, 2006, 2014, 2012, 2013, 2016, 2015, 2010, 2017, 2008, 2018,
       2011, 2019, 2009, 2005, 2000, 2003, 2004, 1995, 2002, 2001])

In [ ]:
dd = pd.read_csv('/content/clean_data.csv')
dd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 816 entries, 0 to 815
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        816 non-null    object
 1   company     816 non-null    object
 2   year        816 non-null    int64
 3   Price       816 non-null    int64
 4   kms_driven  816 non-null    int64
 5   fuel_type   816 non-null    object
dtypes: int64(3), object(3)
memory usage: 38.4+ KB

In [ ]:
dd.describe()

              year         Price     kms_driven
count   816.000000  8.160000e+02     816.000000
mean   2012.444853  4.117176e+05   46275.531863
std       4.002992  4.751844e+05   34297.428044
min    1995.000000  3.000000e+04       0.000000
25%    2010.000000  1.750000e+05   27000.000000
50%    2013.000000  2.999990e+05   41000.000000
75%    2015.000000  4.912500e+05   56818.500000
max    2019.000000  8.500003e+06  400000.000000

# **Building model from here**

In [ ]:
x = df.drop(columns='Price')
y = df['Price']

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import  OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
import pickle

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

In [ ]:
oneHotPreprocessing = ColumnTransformer(
    transformers=[
      ('encoder',OneHotEncoder(handle_unknown='ignore'),['name','company','fuel_type'])
    ],
    remainder='passthrough' #keep other columns as they are
)

In [ ]:
linear_reg = LinearRegression()

In [ ]:
pipe = Pipeline([
    ('oneHotEncode',oneHotPreprocessing),
    ('linearRegression',linear_reg)
])

In [ ]:
pipe.fit(x_train,y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/compose/_column_transformer.py:1667: FutureWarning:
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(

Pipeline(steps=[('oneHotEncode',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('encoder',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['name', 'company',
                                                   'fuel_type'])])),
                ('linearRegression', LinearRegression())])

In [ ]:
pickle.dump(pipe,open('carPricePredectionModel.pkl','wb'))

In [ ]:
pipe.predict(pd.DataFrame([['Maruti Suzuki Swift','Maruti',2019,100,'Petrol']],columns=['name','company','year','kms_driven','fuel_type']))

array([429842.5924466])